/*jshint esversion: 6 */

export const ANSWER_SUBMISSION = {
  START: "ANSWER_SUBMISSION.START",
  SUCCESS: "ANSWER_SUBMISSION.SUCCESS",
  FAILURE: "ANSWER_SUBMISSION.FAILURE"
}

export const FETCH_FRIENDS = {
  START: "FETCH_FRIENDS.START",
  SUCCESS: "FETCH_FRIENDS.SUCCESS",
  FAILURE: "FETCH_FRIENDS.FAILURE"
}

export const LAST_FM_SEARCH = {
  START: "LAST_FM_SEARCH.START",
  SUCCESS: "LAST_FM_SEARCH.SUCCESS",
  FAILURE: "LAST_FM_SEARCH.FAILURE"
}

export const FETCH_GAME = {
  START: "GAME.START",
  SUCCESS: "GAME.SUCCESS",
  FAILURE: "GAME.FAILURE"
}

export const INVITEE = {
  SELECTED: "INVITEE.SELECTED"
}